---
title: A Night in Japan
timezone: Europe/Berlin
collections:
  people:
    title: People
    output: true
    portrait: image
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: people
  values:
    layout: default
email: info@nikitasarejko.com
description: A weblog about Japan
baseurl: 
url: 
twitter_username: nnnnikita
github_username: nikitasarejko
theme: minima
plugins:
- jekyll-feed
